name = "Mustas2"
author = "hues"
version = "0.1"
description = "Mustas Never Die!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c1c9abe9581da83597e8b190fd31a2f3b98e60c56bc3354079b06798a57b191"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = []
datapack-folder = "config\\paxi\\datapacks"
