name = "Mustas2"
author = "hues"
version = "0.1"
description = "Mustas Never Die!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e012d6dd9d79cf28b1e3215d335b0c9373fee3feb10edd2e47c51c65549aa26e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = []
datapack-folder = "config\\paxi\\datapacks"
