name = "Mustas2"
author = "hues"
version = "0.1"
description = "Mustas Never Die!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2589cc48ac04752b7bdcb4247d696655e6277bc04864df5a2fcd1ad0f5091be2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = []
datapack-folder = "config\\paxi\\datapacks"
